spring.application.name=energy-producer

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Open-Meteo API – kostenlos, kein API-Key nötig, Koordinaten Wien
weather.api.url=https://api.open-meteo.com/v1/forecast?latitude=48.2082&longitude=16.3738&current_weather=true