server.port=8080
spring.application.name=energy-rest-api

# PostgreSQL aus Docker Compose
spring.datasource.url=jdbc:postgresql://localhost:5432/energy_db
spring.datasource.username=disysuser
spring.datasource.password=disyspw
spring.datasource.driver-class-name=org.postgresql.Driver

# none = Hibernate ändert das Schema nicht (haben Tabellen manuell erstellt)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect